# Import libraries

In [1]:
import pandas as pd
import psycopg2
import uuid
from datetime import datetime
from tqdm import tqdm
import os
import logging
from sqlalchemy import create_engine, Table, MetaData, Column, Integer, Float, Boolean, String, DateTime, ForeignKey, select, update, bindparam, text
from sqlalchemy.orm import sessionmaker, relationship, declarative_base, clear_mappers
from dotenv import load_dotenv
import matplotlib as plt
from textwrap import dedent
import json

load_dotenv()

True

# Get dotenv variables

In [2]:
# Database information
postgres_user = os.getenv("POSTGRES_USER")
postgres_password = os.getenv("POSTGRES_PASSWORD")
postgres_host = os.getenv("POSTGRES_HOST")
postgres_port = os.getenv("POSTGRES_PORT")
postgres_db = os.getenv("POSTGRES_DB")

# Data path
data_path = os.getenv("DATA_PATH")

# Connect to database

## Create connection to database

In [3]:
try:
    conn = psycopg2.connect(
        database=postgres_db,
        user=postgres_user,
        host=postgres_host,
        password=postgres_password,
        port=postgres_port,
    )
    print("Opened database successfully")
except Exception as e:
    print(f"Connection failed: {e}")

Opened database successfully

In [4]:
# Create engine
engine = create_engine(
    f"postgresql://{postgres_user}:{postgres_password}@{postgres_host}:{postgres_port}/{postgres_db}"
)

# Create a session
session = sessionmaker(bind=engine)()

# Create a MetaData instance
metadata = MetaData()

# Reflect the table
company_table = Table("company", metadata, autoload_with=engine)
news_table = Table("news", metadata, autoload_with=engine)
sentiment_table = Table("sentiment", metadata, autoload_with=engine)
statement_table = Table("financialstatement", metadata, autoload_with=engine)

# Define table

In [5]:
Base = declarative_base()
clear_mappers()

## Define company table

In [6]:
class Company(Base):
    __tablename__ = 'company'
    __table_args__ = {'extend_existing': True}
    id = Column(Integer, primary_key=True)
    createdAt = Column(DateTime)
    updatedAt = Column(DateTime)
    name = Column(String)
    symbol = Column(String)
    description = Column(String)
    logo = Column(String)
    status = Column(Integer)
    exchange = Column(String)
    circulatingStockVolume = Column(Integer)
    listedStockVolume = Column(Integer)
    marketCap = Column(Integer)
    charterCapital = Column(Integer)
    order = Column(Integer)

    news_relation = relationship("News", back_populates="company_relation")
    stock_relation = relationship("Stock", back_populates="company_relation")
    statement_relation = relationship("Statement", back_populates="company_relation")
    report_relation = relationship("Report", back_populates="company_relation")

## Define statement table

In [7]:
class Statement(Base):
    __tablename__ = 'financialstatement'
    __table_args__ = {'extend_existing': True}
    id = Column(Integer, primary_key=True)
    createdAt = Column(DateTime)
    updatedAt = Column(DateTime)
    PE = Column(Float)
    ROA = Column(Float)
    ROE = Column(Float)
    EPS = Column(Float)
    BVPS = Column(Float)
    DAR = Column(Float)
    GOS = Column(Float)
    year = Column(Integer)
    order = Column(Integer) 
    company = Column(String, ForeignKey('company.id'))
    
    # Define the relationship to Company
    company_relation = relationship("Company", back_populates="statement_relation")

## Define news table

In [8]:
class News(Base):
    __tablename__ = 'news'
    __table_args__ = {'extend_existing': True}
    id = Column(Integer, primary_key=True)
    createdAt = Column(DateTime)
    updatedAt = Column(DateTime)
    title = Column(String)
    rawContent = Column(String)
    cleanContent = Column(String)
    url = Column(String)
    banner = Column(String)
    source = Column(String)
    publishedAt = Column(DateTime)
    order = Column(Integer)
    company = Column(String, ForeignKey('company.id'))
    
    # Define the relationship to Company
    company_relation = relationship("Company", back_populates="news_relation")

## Define stock table

In [9]:
class Stock(Base):
    __tablename__ = 'stock'
    __table_args__ = {'extend_existing': True}
    id = Column(Integer, primary_key=True)
    createdAt = Column(DateTime)
    updatedAt = Column(DateTime)
    openingPrice = Column(Float)
    closingPrice = Column(Float)
    ceilingPrice = Column(Float)
    floorPrice = Column(Float)
    highestPrice = Column(Float)
    lowestPrice = Column(Float)
    adjustedPrice = Column(Float)
    change = Column(String)
    tradedValue = Column(Integer)
    tradedVolume = Column(Integer)
    agreedValue = Column(Integer)
    agreedVolume = Column(Integer)
    date = Column(DateTime)
    order = Column(Integer)
    company = Column(String, ForeignKey('company.id'))
    
    # Define the relationship to Company
    company_relation = relationship("Company", back_populates="stock_relation")

## Define report table

In [10]:
class Report(Base):
    __tablename__ = 'report'
    __table_args__ = {'extend_existing': True}
    id = Column(String, primary_key=True)
    createdAt = Column(DateTime)
    updatedAt = Column(DateTime)
    year = Column(Integer)
    quarter = Column(Integer)
    month = Column(Boolean)
    detail = Column(String)
    mScore1 = Column(Float)
    mScore2 = Column(Float)
    fScore1 = Column(Float)
    zScore1 = Column(Float)
    zScore2 = Column(Float)
    zScore3 = Column(Float)
    order = Column(Integer)
    company = Column(String, ForeignKey('company.id'))
    
    # Define the relationship to Company
    company_relation = relationship("Company", back_populates="report_relation")

# Most used function

## Generate UUID function

In [11]:
def generate_uuid():
    id = str(uuid.uuid4())
    created_at = datetime.now()
    updated_at = created_at
    return id, created_at, updated_at

## Get exchange name

In [12]:
def get_exchange_name(exchangeId):
    if exchangeId == 1:
        return "HOSE"
    elif exchangeId == 2:
        return "HNX"
    elif exchangeId == 8:
        return "OTC"
    elif exchangeId == 9:
        return "UPCOM"

In [13]:
def get_company(filename, raw = False):
    df = pd.read_csv(f"{data_path}/raw/{filename}.csv") if raw else pd.read_csv(f"{data_path}/beautiful/{filename}.csv")
    hose_1 = 0
    hnx_2 = 0
    otc_8 = 0
    upcom_9 = 0
    
    exchange_counts = df['ExchangeId'].value_counts()
    
    hose_1 = exchange_counts.get(1, 0)
    hnx_2 = exchange_counts.get(2, 0)
    otc_8 = exchange_counts.get(8, 0)
    upcom_9 = exchange_counts.get(9, 0)

    print(f"HOSE: {hose_1}, HNX: {hnx_2}, OTC: {otc_8}, UPCOM: {upcom_9}")
    print(f"Total: {sum([hose_1, hnx_2, upcom_9])}")

## Read csv file

In [14]:
def read_data(filename, raw = False):
    data = pd.read_csv(f"{data_path}/raw/{filename}.csv") if raw else pd.read_csv(f"{data_path}/beautiful/{filename}.csv")
    return data

## Convert date string to timestamp

In [15]:
def convert_to_timestamp(date_str):
    # Parse the date string
    # date_obj = datetime.strptime(date_str, "%d-%m-%Y")
    date_obj = datetime.strptime(date_str, "%Y-%m-%d")
    # Convert to the desired timestamp format
    timestamp_str = date_obj.strftime("%Y-%m-%d %H:%M:%S.%f")[:-3]
    return timestamp_str

## Calculate ceiling & floor price

In [16]:
def calculate_ceiling_floor_price(exchange, prev_close_price):
    if exchange == "HOSE":
        ceiling_price = prev_close_price * 1.07
        floor_price = prev_close_price * 0.93
    elif exchange == "HNX":
        ceiling_price = prev_close_price * 1.10
        floor_price = prev_close_price * 0.90
    elif exchange == "UPCOM":
        ceiling_price = prev_close_price * 1.15
        floor_price = prev_close_price * 0.85
    else:
        ceiling_price = 0
        floor_price = 0
    return ceiling_price, floor_price

# Import data

## Company

### Compare csv file with database

In [20]:
def compare_data(filename, raw = False):
    results = session.query(Company.symbol).all()
    list_company_db = [result[0] for result in results]

    new_companies = pd.read_csv(f"{data_path}/raw/{filename}.csv") if raw else pd.read_csv(f"{data_path}/beautiful/{filename}.csv")
    list_company_new = new_companies["Symbol"].tolist()

    diff = list(set(list_company_new) - set(list_company_db))

    print(dedent(f"""
        Amount of companies in database: {len(list_company_db)}
        Amount of new/different companies: {len(list_company_new)}
        Amount of companies in new list: {len(diff)}
    """))

In [19]:
compare_data("company/company")

Amount of companies in database: 1565
Amount of new/different companies: 1652
Amount of companies in new list: 87

### Insert company

In [9]:
def insert_company(filename):
    company = pd.read_csv(f"{data_path}/{filename}.csv")
    for _, row in company.iterrows():
        cursor = conn.cursor()
        if row["Name"]  == "N/A" or row["Symbol"] == "N/A":
            continue
        try:
            # Get company information
            name = row["Name"]
            symbol = row["Symbol"]
            category = row["Category"]

            # Check if industry exists
            industry_rows = company[company["Symbol"] == symbol]["Category Name"]
            if not industry_rows.empty:
                industry = industry_rows.values[0]
            else:
                industry = "N/A"

            description = row["Description"]
            logo = row["Logo"]
            exchangeId = row["ExchangeId"]

            if exchangeId == 8:
                continue

            exchange = get_exchange_name(exchangeId)

            # Check if company exists
            cursor.execute(
                """SELECT id, name, symbol FROM company WHERE symbol = %s""", (symbol,)
            )
            company_record = cursor.fetchone()
            # If company exists, skip
            if company_record:
                continue

            # Check if category is empty
            if pd.notna(category) and pd.notnull(category):
                # Check if category exists
                cursor.execute(
                    """SELECT id, name FROM category WHERE name = %s""", (category,)
                )
                category_record = cursor.fetchone()
                # If category does not exist, create it
                if category_record:
                    category_id = category_record[0]
                    category = category_record[1]
                else:
                    category_id, created_at, updated_at = generate_uuid(category)
                    cursor.execute(
                        """INSERT INTO category (id, name, "createdAt", "updatedAt", "order")
                        VALUES (%s, %s, %s, %s, %s)""",
                        (category_id, category, created_at, updated_at, 0),
                    )
                    conn.commit()
                print(f"Category: {category}")
            else:
                category_id = None

            # Check if industry is in database
            if (
                industry != "N/A"
                and industry is not None
                and pd.notna(industry)
                and pd.notnull(industry)
            ):
                cursor.execute(
                    """SELECT id, name FROM industry WHERE name = %s""", (industry,)
                )
                industry_record = cursor.fetchone()
                # If industry does not exist, create it
                if industry_record:
                    industry_id = industry_record[0]
                    industry = industry_record[1]
                else:
                    industry_id, created_at, updated_at = generate_uuid(category)
                    cursor.execute(
                        """INSERT INTO industry (id, name, "createdAt", "updatedAt", category, "order")
                        VALUES (%s, %s, %s, %s, %s, %s)""",
                        (industry_id, industry, created_at, updated_at, category_id, 0),
                    )
                    conn.commit()
                print(f"Industry: {industry}")
            else:
                industry_id = None

            company_id, created_at, updated_at = generate_uuid(category)
            # Insert company record
            cursor.execute(
                """INSERT INTO company (id, name, symbol, description, logo, status, "createdAt", "updatedAt", exchange, industry, "order")
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)""",
                (
                    company_id,
                    name,
                    symbol,
                    description,
                    logo,
                    1,
                    created_at,
                    updated_at,
                    exchange,
                    industry_id,
                    0,
                ),
            )
            conn.commit()
            print(f"Company: {name}")
        except Exception as e:
            conn.rollback()
            print(f"Error: {e}")
            break
        finally:
            cursor.close()

### Get company id

In [17]:
def get_company_id():
    results = session.query(Company.id, Company.symbol).all()
    company_id = {result[1]: result[0] for result in results}
    return company_id

## News

### Get news from CafeF

### Update news relation

### Count news for top company

In [ ]:
metadata = MetaData()

news_table = Table('news', metadata, autoload_with=engine)
stmt = select(news_table.c.company).where(news_table.c.company.isnot(None))
news_df = pd.read_sql(stmt, engine)

company_table = Table('company', metadata, autoload_with=engine)
stmt = select(company_table.c.id, company_table.c.symbol).where(company_table.c.id.isnot(None))
company_df = pd.read_sql(stmt, engine)

company_dict = {
    row["id"]: row["symbol"] for _, row in company_df.iterrows()
}

# count company in news
company_count = news_df["company"].value_counts()

# map company count to company dict
company_count_dict = {
    company_dict[company_id]: count
    for company_id, count in company_count.items()
}

output = pd.DataFrame(company_count_dict.items(), columns=["symbol", "count"])
output[output["symbol"] == "VCB"]

   symbol  count
49    VCB    299

In [ ]:
company_query = text(
    """
    SELECT id, symbol FROM company
    """
)

# Lấy danh sách các công ty từ database
company_df = pd.read_sql(company_query, engine)

# Lưu thành dictionary
company_dict = {
    row["symbol"]: row["id"] for _, row in company_df.iterrows()
}

In [ ]:
company_dict["AAA"]

'1df9a54d-52bd-4322-a2aa-0853b8145997'

In [ ]:
news = pd.read_csv(f"{data_path}/cafef/news.csv")
news.notnull().sum()

Date       100604
Symbols    100688
URL        100688
Title      100604
Content    100604
dtype: int64

In [ ]:
# Define metadata and table object
metadata = MetaData()
news_table = Table('news', metadata, autoload_with=engine)

# Define the update statement with non-conflicting parameter names
stmt = update(news_table).where(news_table.c.title == bindparam('b_title')).values(company=bindparam('b_company'))

data = []
batch_size = 1000
count = 0

for _, row in tqdm(news.iterrows()):
    if pd.isna(row["Symbols"]) or pd.isnull(row["Symbols"]) or pd.isna(row["Title"]) or pd.isnull(row["Title"]):
        continue

    symbol = row["Symbols"]
    title = row["Title"]

    # Lấy id của công ty từ dictionary
    company_id = company_dict.get(symbol)

    if company_id is None:
        continue

    data.append({"b_title": title, "b_company": company_id})
    count += 1

    if count % batch_size == 0:
        with engine.connect() as conn:
            conn.execute(stmt, data)
            conn.commit()
            data = []

if data:
    try:
        with engine.connect() as conn:
            conn.execute(stmt, data)
            conn.commit()
            print("Remaining records updated.")
    except Exception as e:
        print(f"Error occurred: {e}")

100688it [47:48, 35.11it/s]

Remaining records updated.

In [23]:
news = pd.read_csv(f"{data_path}/cafef/news.csv")
news.notnull().sum()
news.isnull().sum()

Date       84
Symbols     0
URL         0
Title      84
Content    84
dtype: int64

In [11]:
null_rows = news[news.isnull().any(axis=1)]
# null_rows.to_csv(f"{data_path}/news_cafef_null.csv", index=False)
null_rows["Symbols"].unique()

array(['BST', 'DIG', 'HDC', 'KDC', 'LHG', 'PVT', 'THG', 'THM', 'THN',
       'THP', 'THS', 'THT', 'TIN'], dtype=object)

In [12]:
banner = pd.read_csv(f"{data_path}/cafef/banner.csv")
banner.notnull().sum()

Symbols    111733
Title      111733
imgUrl     111733
URL        111733
dtype: int64

In [ ]:
for index, row in tqdm(news.iterrows(), total=news.shape[0]):
    cursor = conn.cursor()
    if pd.isna(row["Symbols"]) or pd.isnull(row["Symbols"]) or pd.isna(row["Title"]) or pd.isnull(row["Title"]):
        continue
    try:
        symbol = row["Symbols"]
        url = "https://cafef.vn/" + row["URL"]
        title = row["Title"]
        raw_content = row["Content"]
        published_at = row["Date"]
        source = "CafeF"

        image_url = banner.loc[banner["URL"] == row["URL"], "imgUrl"].values
        if len(image_url) > 0:
            image_url = image_url[0]
        else:
            image_url = None  # or some default value

        # Check if company exists
        cursor.execute(
            """SELECT id, name, symbol FROM company WHERE symbol = %s""", (symbol,)
        )
        company_record = cursor.fetchone()

        # If company does not exist, skip
        if not company_record:
            continue

        company_id = company_record[0]

        # Check if news exists
        cursor.execute("""SELECT id, title FROM news WHERE title = %s""", (title,))
        news_record = cursor.fetchone()

        # If news exists, skip
        if news_record:
            continue

        news_id, created_at, updated_at = generate_uuid("news")
        # Insert news record
        cursor.execute(
            """INSERT INTO news (id, title, "rawContent", url, banner, "publishedAt", source, "createdAt", "updatedAt", company, "order")
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)""",
            (
                news_id,
                title,
                raw_content,
                url,
                image_url,
                published_at,
                source,
                created_at,
                updated_at,
                company_id,
                0,
            ),
        )
        conn.commit()
        print(f"News: {title} for {symbol}")

    except Exception as e:
        conn.rollback()
        print(f"Error: {e}")
        break
    finally:
        cursor.close()

### Update more news

In [39]:
data = read_data("news/matched_datass_vietstock", raw = True)

In [44]:
data.rename(columns={"0": "Date", "1": "Title", "2": "URL", "3": "Symbol", "4": "Content"}, inplace=True)
data.head()

,Date,Title,URL,Symbol,Content
0,13/06/2024,PTP: Ngày đăng ký cuối cùng trả cổ tức bằng ti...,https://vietstock.vn/2024/06/ptp-ngay-dang-ky-...,PTP,PTP: Ngày đăng ký cuối cùng trả cổ tức bằng ti...
1,07/05/2024,PTP: Bổ nhiệm Ông Phạm Tuấn Anh giữ chức vụ Ph...,https://vietstock.vn/2024/05/ptp-bo-nhiem-ong-...,PTP,PTP: Bổ nhiệm Ông Phạm Tuấn Anh giữ chức vụ Ph...
2,03/05/2024,PTP: Nghị quyết Đại hội đồng cổ đông thường ni...,https://vietstock.vn/2024/05/ptp-nghi-quyet-da...,PTP,PTP: Nghị quyết Đại hội đồng cổ đông thường ni...
3,04/04/2024,PTP: Tài liệu họp Đại hội đồng cổ đông,https://vietstock.vn/2024/04/ptp-tai-lieu-hop-...,PTP,PTP: Tài liệu họp Đại hội đồng cổ đôngTài liệu...
4,25/03/2024,PTP: Báo cáo thường niên 2023,https://vietstock.vn/2024/03/ptp-bao-cao-thuon...,PTP,PTP: Báo cáo thường niên 2023Tài liệu đính kèm...

In [ ]:
def import_news(dataframe):
    company_id = get_company_id()

    prev_close_price = {}
    data = []
    batch_size = 10000

    for _, row in tqdm(dataframe.iterrows(), total=dataframe.shape[0]):
        if pd.isna(row["Symbol"]):
            continue

        symbol = row["Symbol"]

        if symbol not in company_id:
            continue

        id, created_at, updated_at = generate_uuid()

        new_news = News(
            id=id,
            createdAt=created_at,
            updatedAt=updated_at,
            title=row["Title"],
            rawContent=row["Content"],
            cleanContent=row["Content"],
            url=row["URL"],
            banner=None,
            source="Vietstock",
            publishedAt=convert_to_timestamp(row["Date"]),
            order=0,
            company=company_id[symbol],
        )

        data.append(new_news)

        if len(data) % batch_size == 0:
            try:
                session.add_all(data)
                session.commit()
                data = []
            except Exception as e:
                session.rollback()
                print(f"Error: {e}")
                break

        # try:
        #     session.add(new_news)
        #     session.commit()
        # except Exception as e:
        #     session.rollback()
        #     print(f"Error: {e}")
        #     break

## Financial statement

In [20]:
statement = pd.read_csv("./data/cafef/statement.csv")
statement.notnull().sum()

Unnamed: 0    19461
Year          19461
Symbol        19461
EPS           19461
BV            19461
PE            19461
ROA           19461
ROE           19461
ROS           19461
GOS           19461
DAR           19461
dtype: int64

In [ ]:
for index, row in tqdm(statement.iterrows(), total=statement.shape[0]):
    cursor = conn.cursor()
    if (
        pd.isna(row["Symbol"])
        or pd.isnull(row["Symbol"])
        or pd.isna(row["Year"])
        or pd.isnull(row["Year"])
    ):
        continue
    try:
        symbol = row["Symbol"]
        year = row["Year"].__str__()
        pe = row["PE"]
        roa = row["ROA"]
        roe = row["ROE"]
        eps = row["EPS"]
        bvps = row["BV"]
        ros = row["ROS"]
        dar = row["DAR"]
        gos = row["GOS"]

        # Check if company exists
        cursor.execute(
            """SELECT id, name, symbol FROM company WHERE symbol = %s""", (symbol,)
        )
        company_record = cursor.fetchone()

        # If company does not exist, skip
        if not company_record:
            continue

        company_id = company_record[0]

        # Check if statement exists
        cursor.execute(
            """SELECT id, company, year from financialstatement WHERE company = %s AND year = %s""",
            (company_id, year),
        )

        statement_record = cursor.fetchone()

        # If statement exists, skip
        if statement_record:
            continue

        statement_id, created_at, updated_at = generate_uuid("statement")
        # Insert statement record
        cursor.execute(
            """INSERT INTO financialstatement (id, year, "PE", "ROA", "ROE", "EPS", "BVPS", "ROS", "DAR", "GOS", "createdAt", "updatedAt", company, "order")
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)""",
            (
                statement_id,
                year,
                pe,
                roa,
                roe,

                
                eps,
                bvps,
                ros,
                dar,
                gos,
                created_at,
                updated_at,
                company_id,
                0,
            ),
        )
        conn.commit()
        print(f"Statement: {year} for {symbol}")
        logging.info(f"Statement: {year} for {symbol}")

    except Exception as e:
        conn.rollback()
        print(f"Error: {e}")
        break
    finally:
        cursor.close()

100%|██████████| 19461/19461 [01:05<00:00, 295.33it/s]

In [18]:
def get_statement():
    results = session.query(Statement.year, Statement.company).all()
    statement = [(result[0], result[1]) for result in results]
    return statement

In [19]:
statement = get_statement()

In [20]:
data = read_data("statement/financialstatement", raw=True)

# get duplicate rows by year and company
duplicate_rows = data[data.duplicated(subset=["company", "year"], keep=False)]

# drop where GOS is equal to 2000
duplicate_rows = duplicate_rows[duplicate_rows["GOS"] != 2000]

# get unique rows by year and company
unique_rows = data.drop_duplicates(subset=["company", "year"], keep=False)
len(duplicate_rows)

39

In [21]:
def get_company_id():
    results = session.query(Company.id).all()
    company_id = [result[0] for result in results]
    results = session.query(Statement.company).all()
    statement_company_id = [result[0] for result in results]
    return company_id, statement_company_id

In [22]:
company_id, statement_company_id = get_company_id()

In [34]:
for id in statement_company_id:
    if id not in company_id:
        print(id)

data_company = data["company"].unique().tolist()
count = 0
for id in company_id:
    if id not in data_company:
        print(id)
        count += 1

print(count)

0b14819c-f5fe-4f3d-ac1f-3c3ca94b3325
0ce8c2b1-6e15-44fe-b80f-710fd9ff9b07
3152f439-f5c1-4c2a-8f16-c6247a8274a8
32e2ed52-967f-4ab2-9eb5-243f85f96bde
4bd0eea8-9343-402b-96b5-277f2cbb603c
62f56980-8aaa-4e90-b126-7d49e4b2863c
6c830f38-5d7b-4a5f-a477-7ae8345e4910
7057f357-cda9-48e0-9acd-3d703ec5018f
711d6452-0724-4307-ae8b-bd674e8f0c75
7d4a9cf8-3f12-48fa-989f-5f438dabf966
885b67f9-f51f-439b-8c25-d13a5ffae346
925e7503-0da4-4e19-afde-2ba0dcc62e07
9a96aa38-9c6f-4375-a154-e369015f5b34
b11b01c0-5779-4e4e-a184-49b08675ebf8
b250e316-eb77-4279-b57b-6879e950992a
b7b1df08-2fb7-4e32-b4bd-0f28d6ae1339
c5fda156-d85d-488a-a12b-7d203bc48c47
da47541a-6561-437a-b4f9-1a1ae989506b
f91a3bc9-1af1-4d3d-8130-25745b96f9f6
19

In [35]:
count = 0
for _, row in data.iterrows():
    company = row["company"]
    year = row["year"].__str__()

    if (year, company) not in statement:
        count += 1
    else:
        continue
        # print(f"Company: {company}, Year: {year}")

print(count)

1615

## Stock

In [14]:
stock = pd.read_csv(f"{data_path}/cafef/stock.csv")
stock.notnull().sum()

Symbol            1774368
Date              1774368
Adjusted Price    1774368
Closing Price     1774368
Opening Price     1774368
Lowest Price      1774368
Highest Price     1774368
Change            1774368
Traded Volume     1774368
Traded Value      1774368
Agreed Volume     1774368
Agreed Value      1774368
dtype: int64

In [8]:
stored_company_id = None
stored_symbol = None

In [32]:
company_query = "SELECT id, symbol, exchange FROM company"
company_info = pd.read_sql(company_query, engine)

# Create the dictionary
company_dict = {
    row['symbol']: {'id': row['id'], 'exchange': row['exchange']}
    for _, row in company_info.iterrows()
}

# Print the resulting dictionary
print(company_dict)

{'ADP': {'id': '5586e757-3de6-41b8-949c-9609afa3307c', 'exchange': 'HOSE'}, 'PTP': {'id': '0aecbefd-de78-4735-b426-5bc09f7f65f5', 'exchange': 'UPCOM'}, 'ST8': {'id': 'ad249263-df58-4739-8178-b9fe63d21e6e', 'exchange': 'HOSE'}, 'BVH': {'id': '0473594f-6d2f-4e30-a2d8-54e0091c685c', 'exchange': 'HOSE'}, 'PVR': {'id': 'e5d8dc57-117a-4e0c-8eb5-a2f09c78873c', 'exchange': 'UPCOM'}, 'NCS': {'id': 'dba2c82d-a257-48ec-ab0a-88b21b6e59f0', 'exchange': 'UPCOM'}, 'TQN': {'id': '9341224a-939e-44d1-b9a0-1e5fc4ea3724', 'exchange': 'UPCOM'}, 'APS': {'id': '8ad6da00-1632-4420-ae22-39a2714d81d2', 'exchange': 'HNX'}, 'BTH': {'id': '89bfe003-85ba-4310-8b12-91d0d362bd0a', 'exchange': 'UPCOM'}, 'AAH': {'id': 'c680324e-d37d-4eec-92f4-3a2b61de1469', 'exchange': 'UPCOM'}, 'SCG': {'id': 'b9be5669-a77e-4ff6-b018-ba32a327e08d', 'exchange': 'HNX'}, 'SBT': {'id': 'd24b3873-3e57-4bac-929f-af05d7809794', 'exchange': 'HOSE'}, 'HLY': {'id': '899b312c-607f-4e07-a408-f5eca3e07a5a', 'exchange': 'UPCOM'}, 'DS3': {'id': 'fdbcda1d-6c56-4b28-bff4-15c11c46b102', 'exchange': 'HNX'}, 'RIC': {'id': 'aaff6570-9e79-447d-a71a-ecdb7964ad10', 'exchange': 'UPCOM'}, 'BSG': {'id': '17173070-0457-4ab1-a601-ca4018e002af', 'exchange': 'UPCOM'}, 'TPB': {'id': 'd055636f-e68b-4347-9820-5565f83629c7', 'exchange': 'HOSE'}, 'CTR': {'id': '7cf87c81-aad4-4ed6-81bb-2ac3e906cd14', 'exchange': 'HOSE'}, 'HRT': {'id': '49c656a9-e600-4bea-b764-df16a01acb3d', 'exchange': 'UPCOM'}, 'KSF': {'id': 'cd9ff6af-ec17-49da-bbce-6c8893b61be6', 'exchange': 'HNX'}, 'SIC': {'id': 'dd985d2b-0396-47cc-8adb-8b00b2e423b5', 'exchange': 'HNX'}, 'HNG': {'id': 'cc7ef3f8-a168-4b8f-8476-aed8004abb4e', 'exchange': 'HOSE'}, 'VPI': {'id': '47cfd3d6-27aa-4f06-aa77-fea22243d294', 'exchange': 'HOSE'}, 'VFS': {'id': 'ef193585-55d8-47f8-9b0d-2ce975c6c70a', 'exchange': 'HNX'}, 'PRE': {'id': 'd4185f26-0887-455f-8a65-a1e664a32587', 'exchange': 'HNX'}, 'VTS': {'id': '28c9c2b4-bdb1-488c-a3f9-40973312e7a6', 'exchange': 'UPCOM'}, 'TUG': {'id': '40856f33-ca7e-4bdd-adcf-c5134d067708', 'exchange': 'UPCOM'}, 'MCI': {'id': 'a76acfab-9567-4f1e-9208-d657d8984cd5', 'exchange': 'UPCOM'}, 'NNG': {'id': '376be9e0-cd46-4b98-86fa-d224b84849d8', 'exchange': 'UPCOM'}, 'SJF': {'id': '2a776b00-a2c2-4635-8f2f-58f4976f870e', 'exchange': 'HOSE'}, 'DHN': {'id': 'ef0da103-886c-48f2-a40c-b801b4de75ea', 'exchange': 'UPCOM'}, 'TVW': {'id': '56ecbe7f-f24c-4217-812b-df37a10874da', 'exchange': 'UPCOM'}, 'RGC': {'id': 'f5d9109b-a306-47c2-8962-9a7b05367ab3', 'exchange': 'UPCOM'}, 'DSV': {'id': '736faeb7-4644-4ed4-a412-1fdab3b63e73', 'exchange': 'UPCOM'}, 'DTV': {'id': '62f56980-8aaa-4e90-b126-7d49e4b2863c', 'exchange': 'UPCOM'}, 'CAV': {'id': '3152f439-f5c1-4c2a-8f16-c6247a8274a8', 'exchange': 'HOSE'}, 'GEE': {'id': 'b7b1df08-2fb7-4e32-b4bd-0f28d6ae1339', 'exchange': 'UPCOM'}, 'GTH': {'id': 'ed0711ef-85c9-4349-ae39-241e002e5c3e', 'exchange': 'UPCOM'}, 'HEM': {'id': 'd9bb6cbd-9526-4e97-91c6-52c26ae76bf1', 'exchange': 'UPCOM'}, 'HGW': {'id': '7057f357-cda9-48e0-9acd-3d703ec5018f', 'exchange': 'UPCOM'}, 'HTP': {'id': 'aa2227a3-eb9c-4938-8d31-2ae919a50e61', 'exchange': 'HNX'}, 'SHB': {'id': 'd6d9f999-41ac-40b7-9d4b-ce08f2101633', 'exchange': 'HOSE'}, 'HTW': {'id': '09b24988-fa13-4fc6-921d-ecffbc2cb76c', 'exchange': 'UPCOM'}, 'BLW': {'id': 'e19f8115-5c4e-47b6-95eb-b1ff5f423f84', 'exchange': 'UPCOM'}, 'TDN': {'id': 'a008ef61-9d60-4024-bbd1-151fbf8fd557', 'exchange': 'HNX'}, 'KLM': {'id': '0ce8c2b1-6e15-44fe-b80f-710fd9ff9b07', 'exchange': 'UPCOM'}, 'TDI': {'id': '711d6452-0724-4307-ae8b-bd674e8f0c75', 'exchange': 'UPCOM'}, 'TC6': {'id': '70d6659c-0b15-445f-9de9-f1d5b8753bf9', 'exchange': 'HNX'}, 'PTN': {'id': 'f91a3bc9-1af1-4d3d-8130-25745b96f9f6', 'exchange': 'UPCOM'}, 'MCD': {'id': '32e2ed52-967f-4ab2-9eb5-243f85f96bde', 'exchange': 'UPCOM'}, 'ABB': {'id': 'e8b90618-cbc8-4857-ab1a-5060af86348e', 'exchange': 'UPCOM'}, 'BCB': {'id': 'a4261534-438e-4152-b09e-f52ec09f0857', 'exchange': 'UPCOM'}, 'USD': {'id': '76a6921e-f572-4764-be79-f469f2a5f9d4', 'exchange': 'UPCOM'}, 'V11': {'id': '7ace9df8-c5e7-4762-95e0-1b308cc979d6', 'exchange': 'UPCOM'}, 'V12': {'id': '1c980ded-a915-47a6-bb17-bd7fa862809e', 'exchange': 'HNX'}, 'V15': {'id': '0f7abf47-a43a-4645-8963-f0243214fb17', 'exchange': 'UPCOM'}, 'V21': {'id': 'c127cc24-12b3-46e7-80b9-f35607e37100', 'exchange': 'HNX'}, 'VAF': {'id': '5efb23c1-ea9b-45fb-ad59-f4f15adbac56', 'exchange': 'HOSE'}, 'VAV': {'id': 'ef8a2f13-805f-4553-a253-cbf5fb479bd5', 'exchange': 'UPCOM'}, 'VBB': {'id': 'cc06e928-295c-4379-be8e-1d166be28dd7', 'exchange': 'UPCOM'}, 'VBC': {'id': '21f845dc-dec0-449a-bee0-a1c131f47e30', 'exchange': 'HNX'}, 'VBG': {'id': '057bb320-f881-4ece-861f-472c54190857', 'exchange': 'UPCOM'}, 'BHG': {'id': 'dcc87a87-1064-4717-a86d-5337c6c52bd8', 'exchange': 'UPCOM'}, 'BID': {'id': '718481a4-13a9-47a1-b925-450cf4b7bbd9', 'exchange': 'HOSE'}, 'BVB': {'id': '3d36bf9a-f0cb-47cb-a826-c9c77439b4c2', 'exchange': 'UPCOM'}, 'D17': {'id': '784d3421-130d-410c-ac4b-b7b56a1b09d3', 'exchange': 'UPCOM'}, 'VNP': {'id': 'e8ce8282-2dcf-48e7-8880-86d5cf85eb0e', 'exchange': 'UPCOM'}, 'DTE': {'id': '5fd1e73d-0f2f-4af4-b888-a642a28019b9', 'exchange': 'UPCOM'}, 'EIB': {'id': '4696b29b-f094-4046-9b84-9efa2778f219', 'exchange': 'HOSE'}, 'GH3': {'id': 'bcf7dba2-bce9-4a83-b172-6fbcd7447bff', 'exchange': 'UPCOM'}, 'GPC': {'id': '420355e8-b0a1-4918-a504-f4f347d5eeb1', 'exchange': 'UPCOM'}, 'HDB': {'id': '2867a544-9598-4f45-8679-5ebbd435e1b7', 'exchange': 'HOSE'}, 'HHS': {'id': '4e79c59d-fa09-4a5d-90e8-cf5f20a4c886', 'exchange': 'HOSE'}, 'AG1': {'id': '44158d8f-7db3-48a8-8558-c94d9a27c888', 'exchange': 'UPCOM'}, 'AGE': {'id': 'b250e316-eb77-4279-b57b-6879e950992a', 'exchange': 'UPCOM'}, 'LNC': {'id': '27e48380-16a5-410e-92c9-ca42f6f9d207', 'exchange': 'UPCOM'}, 'LPB': {'id': 'cda0ad7a-2b6c-4fa8-b231-453740375bd4', 'exchange': 'HOSE'}, 'MSB': {'id': 'e477af54-d43d-4bb4-8d6a-07b3677c2f0e', 'exchange': 'HOSE'}, 'NCG': {'id': '1ae2f665-8159-47be-9a62-737c21998670', 'exchange': 'UPCOM'}, 'NEM': {'id': 'a8a96555-f196-4b33-a2fd-5355766ec5c4', 'exchange': 'UPCOM'}, 'NVB': {'id': 'bd6f6ddb-d4c1-40d3-b397-5c5c2e714f88', 'exchange': 'HNX'}, 'PGB': {'id': '88e05b3a-53a9-4253-af29-039f0648554d', 'exchange': 'UPCOM'}, 'PLE': {'id': '9f2ca009-a727-408a-8630-8b9f3cd4fc8a', 'exchange': 'UPCOM'}, 'DTB': {'id': 'fc20446f-6a63-47dd-8fab-bbe199884d1d', 'exchange': 'UPCOM'}, 'PTX': {'id': '49855722-8e72-4e41-9700-8b59d02b8557', 'exchange': 'UPCOM'}, 'PV2': {'id': '4483ae1f-e940-4d37-8d87-5482d2cc2eb8', 'exchange': 'HNX'}, 'PVA': {'id': 'be1f1175-3a52-4400-97a9-285fd4146df8', 'exchange': 'UPCOM'}, 'QNT': {'id': 'ebc9c80d-3ec4-4d45-9736-8fa79481ac8c', 'exchange': 'UPCOM'}, 'SHE': {'id': '85b0666e-85e0-495d-83cf-65f93e837896', 'exchange': 'HNX'}, 'TBW': {'id': 'be360f44-91d9-438e-9366-a95f3d370f5b', 'exchange': 'UPCOM'}, 'SSB': {'id': '340ce3a5-2aae-4419-9392-3b4eae36767f', 'exchange': 'HOSE'}, 'SZG': {'id': '3ea91339-a87e-4dc9-8f43-c2c37c533e4b', 'exchange': 'UPCOM'}, 'VAB': {'id': 'bafd8f48-e6fe-4f2d-bbf8-83a49398adfd', 'exchange': 'UPCOM'}, 'VIB': {'id': '7b346be4-9f1e-4ec1-98e8-a23696c7feca', 'exchange': 'HOSE'}, 'VPB': {'id': '8d7ad3b4-6145-40ff-a2d8-0487aacaac2a', 'exchange': 'HOSE'}, 'VPW': {'id': '0de6cecc-5b7d-49b1-ba01-ef9fb0fa722d', 'exchange': 'UPCOM'}, 'VCE': {'id': '63336435-286f-4ead-a67d-88114c1a0625', 'exchange': 'UPCOM'}, 'HSV': {'id': 'a2ecfd67-bb0f-49da-9824-475a72c75f4d', 'exchange': 'UPCOM'}, 'VTT': {'id': '058be867-4cf6-4f07-85f8-f538eb156eff', 'exchange': 'HNX'}, 'VW3': {'id': 'b18de2f7-c3ad-4b3e-8c97-38d766927c6d', 'exchange': 'UPCOM'}, 'XDC': {'id': 'da47541a-6561-437a-b4f9-1a1ae989506b', 'exchange': 'UPCOM'}, 'A32': {'id': '688b224b-3453-44d8-8ff1-45ba88aea48f', 'exchange': 'UPCOM'}, 'AAA': {'id': '1df9a54d-52bd-4322-a2aa-0853b8145997', 'exchange': 'HOSE'}, 'AAM': {'id': 'd3bfa561-b9a3-423b-be10-266acb77bb2c', 'exchange': 'HOSE'}, 'AAS': {'id': 'c503969a-d09b-492c-8e59-19c8e21fea26', 'exchange': 'UPCOM'}, 'ACB': {'id': 'ddb377c4-94ff-46be-82e3-a9707bc37a6d', 'exchange': 'HOSE'}, 'AAT': {'id': '636c97e2-89ea-46b4-a76a-8bab0fb32e90', 'exchange': 'HOSE'}, 'AAV': {'id': 'b050fa34-7243-4642-83a2-82571af909e9', 'exchange': 'HNX'}, 'ABC': {'id': '5a1875d9-37e3-47a1-b917-57411f967376', 'exchange': 'UPCOM'}, 'ABI': {'id': '6aab35da-4da7-4344-80c1-b56ff89a28d9', 'exchange': 'UPCOM'}, 'ABR': {'id': '9774f58f-292f-471b-a0d7-263f73ea5a33', 'exchange': 'HOSE'}, 'ABS': {'id': '1072f96e-035a-4cac-9b42-af89c4abb6b8', 'exchange': 'HOSE'}, 'ABT': {'id': 'a9fed4f5-7abb-47a9-ab4c-465c0425dcb3', 'exchange': 'HOSE'}, 'ABW': {'id': '4bd0eea8-9343-402b-96b5-277f2cbb603c', 'exchange': 'UPCOM'}, 'ACC': {'id': 'c7359839-3ef6-491e-9394-25d189176bd8', 'exchange': 'HOSE'}, 'ACE': {'id': '6a7262c1-2254-4211-a5ce-c86250d30a16', 'exchange': 'UPCOM'}, 'AMP': {'id': '28f60d53-4859-4f53-96f5-a7942db28005', 'exchange': 'UPCOM'}, 'ACG': {'id': '85d65674-2301-4f83-b738-81a84eeb6774', 'exchange': 'HOSE'}, 'ACL': {'id': 'e0dd60e6-fed5-486c-855c-67b63bf90883', 'exchange': 'HOSE'}, 'ACM': {'id': 'acfdb6fc-5872-47c1-8566-0a5f71fc9198', 'exchange': 'UPCOM'}, 'ACS': {'id': 'fca7b3f1-ef59-467e-9fda-2eb7a7315584', 'exchange': 'UPCOM'}, 'ACV': {'id': '0945d117-20da-464c-b5e5-265563636ab7', 'exchange': 'UPCOM'}, 'ADC': {'id': '6207baf4-e898-4e1c-aeca-a21633d94e36', 'exchange': 'HNX'}, 'ADG': {'id': '58ffa4f6-990b-4a80-849b-da7832626486', 'exchange': 'HOSE'}, 'ADS': {'id': 'b292e524-7351-450a-b78d-420c9228c6c6', 'exchange': 'HOSE'}, 'AFX': {'id': '8294ad82-788d-43cc-b043-bb13935663b1', 'exchange': 'UPCOM'}, 'AGF': {'id': '28a5c98c-8319-4b47-8b92-53ae1dedfb16', 'exchange': 'UPCOM'}, 'AGG': {'id': '339bffe6-5a85-4a50-bcda-00467bf9ef77', 'exchange': 'HOSE'}, 'AGM': {'id': 'e5a76bd3-0de4-49fa-a710-a375906bcfb7', 'exchange': 'HOSE'}, 'AGP': {'id': '3ad54e16-2b55-4229-9f10-b3a19fa78214', 'exchange': 'UPCOM'}, 'AGR': {'id': 'e6005a56-01c0-480a-947d-a4e4d1829928', 'exchange': 'HOSE'}, 'AGX': {'id': 'd701e4a3-112b-48e0-a427-359761b80a9b', 'exchange': 'UPCOM'}, 'AIC': {'id': '7d4a9cf8-3f12-48fa-989f-5f438dabf966', 'exchange': 'UPCOM'}, 'ALT': {'id': 'd2cd8b68-847d-4fbd-91ec-0622dc2f0e8c', 'exchange': 'HNX'}, 'APH': {'id': 'ab2df6d7-94d5-4695-80ba-9928e09b5e4d', 'exchange': 'HOSE'}, 'ALV': {'id': '033c9381-f684-42c8-9e37-26a5b43a4936', 'exchange': 'UPCOM'}, 'AMC': {'id': '6e1fa574-4f2a-4791-9835-014aecb13145', 'exchange': 'HNX'}, 'AME': {'id': 'd5837a3d-32a7-49e5-8e6f-16cf84e7d55a', 'exchange': 'HNX'}, 'AMS': {'id': '5cfad1e0-14eb-4015-aaba-c01caf6432fc', 'exchange': 'UPCOM'}, 'AMV': {'id': 'b9d409c7-c627-4ac0-a195-134e84d28ff8', 'exchange': 'HNX'}, 'ANT': {'id': '724a1971-a926-4745-8e8c-6012d82662b3', 'exchange': 'UPCOM'}, 'ANV': {'id': 'fabfcda4-2c70-4e73-86b8-5807591c2dac', 'exchange': 'HOSE'}, 'APC': {'id': 'ab004d80-4508-4b55-8b63-42c33873cf89', 'exchange': 'HOSE'}, 'APF': {'id': 'e8657989-fb0d-4886-834e-e892b4349114', 'exchange': 'UPCOM'}, 'APG': {'id': 'ed9bfac9-00de-4fc9-8b99-07f5d6295152', 'exchange': 'HOSE'}, 'API': {'id': '71ce7cab-8462-447c-8652-919ec7dd0cd9', 'exchange': 'HNX'}, 'APL': {'id': 'a08f032e-6383-4db5-b3d7-a4244d363b62', 'exchange': 'UPCOM'}, 'APP': {'id': '4ca84ae3-88f9-4908-8d58-550f87a749ff', 'exchange': 'UPCOM'}, 'APT': {'id': '11c3e136-f832-4767-b7d8-4a0ed56b55a7', 'exchange': 'UPCOM'}, 'ARM': {'id': 'b97a73ad-f2b4-409a-a160-936a2e67d5bf', 'exchange': 'HNX'}, 'ASG': {'id': 'f2c8b147-8218-4442-af53-d4eec597556f', 'exchange': 'HOSE'}, 'ASM': {'id': '022888a5-b2f3-4343-96a8-5d575e4b38eb', 'exchange': 'HOSE'}, 'ASP': {'id': '384e1898-5226-4ae4-b814-727c82430f51', 'exchange': 'HOSE'}, 'AST': {'id': 'c0477d35-cc61-4efb-932d-c678518575bc', 'exchange': 'HOSE'}, 'BCR': {'id': '4487ff45-dc22-40a7-80f7-a461eb565166', 'exchange': 'UPCOM'}, 'ATA': {'id': '76bf28d1-c428-49f1-ac13-0028ed80b802', 'exchange': 'UPCOM'}, 'BBM': {'id': 'ff7904ac-75cb-4704-8b5b-7fef3db57e18', 'exchange': 'UPCOM'}, 'ATB': {'id': '3b5326ba-5c61-4a5d-88f6-ba9b0135f507', 'exchange': 'UPCOM'}, 'ATG': {'id': '1f2742a7-f36d-411b-8eb7-941610af8f9c', 'exchange': 'UPCOM'}, 'ATS': {'id': '4d729d1b-4e66-41e4-858d-8d0e1d521d20', 'exchange': 'HNX'}, 'AVC': {'id': 'b81581f0-06ae-495c-8ebe-7564839d9c39', 'exchange': 'UPCOM'}, 'BAB': {'id': '3ab6322b-864d-4acc-9282-81cf1f8b4e34', 'exchange': 'HNX'}, 'BAF': {'id': 'fa88b3e9-a469-4387-a71c-e0d98bfcd708', 'exchange': 'HOSE'}, 'BAL': {'id': '264ac384-23fd-477e-babd-fa577cadf672', 'exchange': 'UPCOM'}, 'BAX': {'id': 'adb82035-1117-4115-86a1-414ba020040e', 'exchange': 'HNX'}, 'BCV': {'id': 'ec52f65c-886d-4b11-b018-d79ba4de67e9', 'exchange': 'UPCOM'}, 'BBC': {'id': '0a5a1a44-e0a9-4151-a1f0-560e5d808497', 'exchange': 'HOSE'}, 'BBH': {'id': 'a0980efa-93f1-4aed-b27f-9b2e4cf475a6', 'exchange': 'UPCOM'}, 'BBS': {'id': 'd5def331-4ab9-43db-ae58-ba14bc66b03e', 'exchange': 'HNX'}, 'BBT': {'id': 'f9e65c5a-efbb-4a87-ac44-e05dc5e07070', 'exchange': 'UPCOM'}, 'BCA': {'id': 'ad695cad-c29f-4d8a-a1fc-55de5721d86e', 'exchange': 'UPCOM'}, 'BCC': {'id': '36120232-b17f-4f60-a06b-b315a26735d9', 'exchange': 'HNX'}, 'BCE': {'id': '622de7ad-5d50-4e12-b5fd-f57023ef1d0e', 'exchange': 'HOSE'}, 'BCF': {'id': 'ba4fd046-a176-41fd-bad5-80b801d4cef2', 'exchange': 'HNX'}, 'BCG': {'id': 'f09b4a01-671c-4450-994d-f9cbb1cc3e44', 'exchange': 'HOSE'}, 'BCM': {'id': 'c8576094-e542-42fb-aaff-6416aad99bb4', 'exchange': 'HOSE'}, 'BCP': {'id': '01cf8140-d25b-4d84-8150-7d2b21ba70fb', 'exchange': 'UPCOM'}, 'BMI': {'id': 'e762c196-abdd-42a3-8346-2407b474f10d', 'exchange': 'HOSE'}, 'BDB': {'id': '589f4cb3-cf0c-4ae4-a9a8-6d3f8a2b4d82', 'exchange': 'HNX'}, 'BDG': {'id': 'c9e0d18b-61fc-4336-8f78-d11b926f6819', 'exchange': 'UPCOM'}, 'BDT': {'id': 'f4d96529-cdae-4983-a76f-5b60c9df6072', 'exchange': 'UPCOM'}, 'BDW': {'id': '6b30bd91-f27a-4c5d-8314-8a6694d6ae68', 'exchange': 'UPCOM'}, 'BED': {'id': '737054ea-328f-4e7b-94bc-0c4c2e498f2b', 'exchange': 'HNX'}, 'BEL': {'id': '117cc016-d40d-4994-94c2-f14703855747', 'exchange': 'UPCOM'}, 'BFC': {'id': 'bc21dd84-765c-404a-ae1d-d1bef85e1783', 'exchange': 'HOSE'}, 'BGW': {'id': '4dcf2832-4a78-479c-9a03-d315fde1a04c', 'exchange': 'UPCOM'}, 'BHA': {'id': '23aeda2c-d712-4744-8344-3a9fa465248e', 'exchange': 'UPCOM'}, 'BHC': {'id': 'b3411196-26f9-400f-9b42-b29d6115ff7d', 'exchange': 'UPCOM'}, 'BHI': {'id': '5f667be3-8063-4e5f-80b4-e8f83edcf5a1', 'exchange': 'UPCOM'}, 'BHK': {'id': '60f236c9-3434-4b7a-a650-11df16f72290', 'exchange': 'UPCOM'}, 'BHN': {'id': '0ed4588b-4dc4-4bcc-8eb6-d6e1fcdee3ff', 'exchange': 'HOSE'}, 'BHP': {'id': '6b36f610-9b75-4c88-bb56-d1a5719add77', 'exchange': 'UPCOM'}, 'BIC': {'id': 'f3c653e7-5508-4d4d-9fec-2172ee75a4d0', 'exchange': 'HOSE'}, 'BIG': {'id': '4f2e10bc-eaf2-4135-94a0-65306cf3a980', 'exchange': 'UPCOM'}, 'BII': {'id': 'f22c9edf-e464-4ec8-a0fa-7a788d2e6235', 'exchange': 'UPCOM'}, 'BIO': {'id': 'e5d797dc-b371-48be-a971-b17e61affa0d', 'exchange': 'UPCOM'}, 'BKC': {'id': 'dcd6edbe-75c6-42eb-9a6f-b3de8de8d289', 'exchange': 'HNX'}, 'BMG': {'id': 'ac4123bc-c35b-4068-ab4d-47096708c459', 'exchange': 'UPCOM'}, 'BKG': {'id': '323268db-77fc-42bb-922a-30625053a8ad', 'exchange': 'HOSE'}, 'BLF': {'id': '4d457384-27b3-410f-b3e9-bf6c464911bb', 'exchange': 'HNX'}, 'BLI': {'id': 'c5fda156-d85d-488a-a12b-7d203bc48c47', 'exchange': 'UPCOM'}, 'BLN': {'id': '7808feca-2c0b-4785-8e89-42fa869a8230', 'exchange': 'UPCOM'}, 'BLT': {'id': 'ad8193c4-6bb0-4102-9c7c-cfaf5a2e5140', 'exchange': 'UPCOM'}, 'BMC': {'id': '41f3ec8c-3f1e-4ddd-b935-e8c93d9789e2', 'exchange': 'HOSE'}, 'BMD': {'id': 'fa1aa306-d438-4691-bb4b-281c35e84a3b', 'exchange': 'UPCOM'}, 'BMF': {'id': '28169e3c-3042-4065-b42d-0f4eaaf49f83', 'exchange': 'UPCOM'}, 'BKH': {'id': 'bcee256e-98e1-4e9a-bcb4-75fcb924c457', 'exchange': 'UPCOM'}, 'BMJ': {'id': 'e4f5cce5-40a2-4b68-8ef9-916a899174df', 'exchange': 'UPCOM'}, 'BMN': {'id': 'f31c0acb-5c9b-4518-88a3-67a9361298af', 'exchange': 'UPCOM'}, 'BMP': {'id': '03835c0f-0b9f-4473-8d15-06f86b265b1d', 'exchange': 'HOSE'}, 'BMS': {'id': '0b14819c-f5fe-4f3d-ac1f-3c3ca94b3325', 'exchange': 'UPCOM'}, 'BMV': {'id': '2897f825-dc37-4d4a-be2a-711f62e8a255', 'exchange': 'UPCOM'}, 'BNA': {'id': '9b06ffaf-c281-45f5-a484-84302d1772f5', 'exchange': 'HNX'}, 'BNW': {'id': '7dd9cb3b-4564-4df7-b299-b6d2c3ff4651', 'exchange': 'UPCOM'}, 'BOT': {'id': '8d5c451c-e4ca-467d-b5ac-5086042f02cd', 'exchange': 'UPCOM'}, 'BPC': {'id': '8006fcc4-0ab1-48ba-b938-fa8a4369c196', 'exchange': 'HNX'}, 'BQB': {'id': '85122fce-abe2-47c6-afe4-b456d145d449', 'exchange': 'UPCOM'}, 'BRC': {'id': '93e54b1b-1f9f-42b7-a3c4-8c27264ee88a', 'exchange': 'HOSE'}, 'BRR': {'id': '8e656815-5f01-4793-b335-5c4b280ff64f', 'exchange': 'UPCOM'}, 'BRS': {'id': 'de305b80-5783-404c-8854-1a173e7f1a05', 'exchange': 'UPCOM'}, 'BSA': {'id': '72715452-4d74-40bc-9732-dcef73305c2d', 'exchange': 'UPCOM'}, 'BSC': {'id': '66274262-de56-4daf-8f59-821ca5fb3eda', 'exchange': 'HNX'}, 'BSD': {'id': 'dacc6396-ed7b-4ebe-ab3f-90290616dd56', 'exchange': 'UPCOM'}, 'BSH': {'id': 'dffd45fc-e908-4205-92b7-d3c0ea1a32e4', 'exchange': 'UPCOM'}, 'BSI': {'id': '4368ea10-d19a-4917-8e33-ff578fcd9f3e', 'exchange': 'HOSE'}, 'BSL': {'id': 'd2588408-3843-4e43-97c6-f60b121fe825', 'exchange': 'UPCOM'}, 'BSP': {'id': 'a7da185a-e1e8-4160-9a3d-8eaed5677f3c', 'exchange': 'UPCOM'}, 'BSR': {'id': '9cd265f2-527c-4f0b-8834-2623db7661a6', 'exchange': 'UPCOM'}, 'BST': {'id': '18d1d013-2e74-4d6b-9ed2-949ee4a48654', 'exchange': 'HNX'}, 'BT1': {'id': 'f1c79195-6dfd-4332-a0cf-0f8e506d9cdd', 'exchange': 'UPCOM'}, 'BTB': {'id': '1a5a0ea3-0b8c-4aec-a317-5b56a8079d34', 'exchange': 'UPCOM'}, 'BTD': {'id': '389b40f6-fd3e-43dc-b539-a1e11b6dcfca', 'exchange': 'UPCOM'}, 'BTG': {'id': 'c785ed2a-5398-4529-84c3-2aa6dd89f89a', 'exchange': 'UPCOM'}, 'BTN': {'id': 'bd81e00a-0dae-4013-aec8-a3f4b810c5cb', 'exchange': 'UPCOM'}, 'BTP': {'id': 'c856ad98-1d13-4fdf-960b-cbe946685a68', 'exchange': 'HOSE'}, 'BSQ': {'id': '22d73b6e-7ca2-4b84-9dad-431027d9c833', 'exchange': 'UPCOM'}, 'BTS': {'id': '1182c785-fb8f-4159-8f4a-ce27feea4cb6', 'exchange': 'HNX'}, 'BTT': {'id': '20626f40-c77d-438b-97c9-2fea82e4404e', 'exchange': 'HOSE'}, 'BTU': {'id': '72906e9d-2191-49bc-bd4c-a69c234623a3', 'exchange': 'UPCOM'}, 'BTV': {'id': '2c14f788-31e8-4fc0-aa9e-6d10dcb91aab', 'exchange': 'UPCOM'}, 'BTW': {'id': 'f8d144e8-3363-4907-ad5e-286bb67a5792', 'exchange': 'HNX'}, 'BVG': {'id': 'c8b90d5a-cca1-4c64-bdd1-551069100c79', 'exchange': 'UPCOM'}, 'BVL': {'id': '5aed1e32-6a27-4033-9a7d-a3fb575fa4ca', 'exchange': 'UPCOM'}, 'BVN': {'id': '1eaa9f99-67ab-4b6b-a53a-ee31329357d9', 'exchange': 'UPCOM'}, 'BVS': {'id': '36cec99a-0bd4-4b8c-9692-8273a8f7e6a5', 'exchange': 'HNX'}, 'DAT': {'id': '98866e7b-9cbe-4f6f-a9e2-bfa43d583f00', 'exchange': 'HOSE'}, 'BWA': {'id': '0a94e87c-9926-43be-b842-b751a5765a7a', 'exchange': 'UPCOM'}, 'BWE': {'id': '5f579947-438c-4006-aed2-94f3b320ce8d', 'exchange': 'HOSE'}, 'CBS': {'id': '2e2b5f93-ab28-4e9b-b206-6f25b9bc87c2', 'exchange': 'UPCOM'}, 'BWS': {'id': '8c90b9d9-1fbb-445a-8ca9-adf4da7001ed', 'exchange': 'UPCOM'}, 'BXH': {'id': '8b9a90c8-0e9b-4db1-a071-910f617daeb7', 'exchange': 'HNX'}, 'C21': {'id': '10012989-27a7-4c8e-bb71-e54c1638a3a6', 'exchange': 'UPCOM'}, 'C22': {'id': '770870b0-2bb6-4a6b-a6b2-68130f22465b', 'exchange': 'UPCOM'}, 'C32': {'id': '6eebcce3-d9af-4c09-9481-d444fd760a95', 'exchange': 'HOSE'}, 'C47': {'id': '3a799f22-fff2-48aa-8482-90348871248f', 'exchange': 'HOSE'}, 'CAT': {'id': '15268e87-d1ff-47e7-9dd9-1ea3d84542d9', 'exchange': 'UPCOM'}, 'C4G': {'id': 'b1fcf66e-fd10-487f-bc35-7467e482fe2f', 'exchange': 'UPCOM'}, 'CC1': {'id': 'd70ba049-b988-49f9-b97e-651a885cadf0', 'exchange': 'UPCOM'}, 'C69': {'id': '4fc5faa0-5991-4ecc-8c89-8143eb8eb0a3', 'exchange': 'HNX'}, 'C92': {'id': 'd98ac637-0fea-4b6e-9f62-359f77c68e6e', 'exchange': 'UPCOM'}, 'CAB': {'id': '9c1108ae-4b17-478a-8824-e543d8021f30', 'exchange': 'UPCOM'}, 'CAD': {'id': '36613503-0393-4547-912c-bdf904ed6963', 'exchange': 'UPCOM'}, 'CAG': {'id': 'b3002bba-c436-4b85-ad86-e64f45c2a467', 'exchange': 'HNX'}, 'CAN': {'id': 'bc2d89d7-a17d-41ff-9b02-5ad52c42aeb6', 'exchange': 'HNX'}, 'CAP': {'id': '3b86166f-cb46-4e2a-9a57-fe7bb8b30474', 'exchange': 'HNX'}, 'CAR': {'id': '44

In [15]:
data = []
prev_close_price = {}
batch_size = 1000
insert_query = text("""
INSERT INTO stock (id, "date", "openingPrice", "closingPrice", "highestPrice", "lowestPrice", "ceilingPrice", "floorPrice", "adjustedPrice", change, "tradedVolume", "tradedValue", "agreedVolume", "agreedValue", "createdAt", "updatedAt", company, "order")
VALUES (:id, :date, :openingPrice, :closingPrice, :highestPrice, :lowestPrice, :ceilingPrice, :floorPrice, :adjustedPrice, :change, :tradedVolume, :tradedValue, :agreedVolume, :agreedValue, :createdAt, :updatedAt, :company, :order)
""")

count = 0
for index, row in tqdm(stock.iterrows(), total=stock.shape[0]):
    if pd.isna(row["Symbol"]) or pd.isna(row["Closing Price"]):
        continue

    symbol = row["Symbol"]
    close_price = row["Closing Price"]
    open_price = row["Opening Price"]
    highest_price = row["Highest Price"]
    lowest_price = row["Lowest Price"]
    change_price = row["Adjusted Price"]
    change = row["Change"]
    traded_volume = row["Traded Volume"]
    traded_value = row["Traded Value"]
    agreed_volume = row["Agreed Volume"]
    agreed_value = row["Agreed Value"]
    date = convert_to_timestamp(row["Date"])

    # Lấy exchange từ dictionary
    company_info = company_dict.get(symbol, {})
    exchange = company_info.get("exchange")
    company_id = company_info.get("id")

    # Lấy giá đóng cửa của ngày trước để tính giá trần và giá sàn
    if symbol in prev_close_price:
        ceiling_price, floor_price = calculate_ceiling_floor_price(
            exchange, prev_close_price[symbol]
        )
    else:
        ceiling_price, floor_price = 0, 0

    prev_close_price[symbol] = close_price

    # Tạo id, created_at, updated_at
    stock_id, created_at, updated_at = generate_uuid("stock")

    # Thêm dữ liệu vào danh sách
    data.append(
        {
            "id": stock_id,
            "date": date,
            "openingPrice": open_price,
            "closingPrice": close_price,
            "highestPrice": highest_price,
            "lowestPrice": lowest_price,
            "ceilingPrice": ceiling_price,
            "floorPrice": floor_price,
            "adjustedPrice": change_price,
            "change": change,
            "tradedVolume": traded_volume,
            "tradedValue": traded_value,
            "agreedVolume": agreed_volume,
            "agreedValue": agreed_value,
            "createdAt": created_at,
            "updatedAt": updated_at,
            "company": company_id,
            "order": 0,
        }
    )
    count += 1

    if count % batch_size == 0:
        with engine.connect() as conn:
            conn.execute(insert_query, data)
            conn.commit()
            data = []

if data:
    try:
        with engine.connect() as conn:
            conn.execute(insert_query, data)
            conn.commit()
            print("Remaining records inserted.")
    except Exception as e:
        print(f"Error occurred: {e}")

print("Data insertion complete.")

100%|██████████| 1774368/1774368 [08:56<00:00, 3305.19it/s]

Remaining records inserted.
Data insertion complete.

In [18]:
data = read_data("stock/processed_prices", raw=True)
# sort data by company, date
data = data.sort_values(by=["symbols", "Date"])
data = data.reset_index(drop=True)
data.keys().tolist()

['symbols',
 'Date',
 'open',
 'close',
 'adjust',
 'high',
 'low',
 'change',
 'GiaTriKhopLenh',
 'KhoiLuongKhopLenh',
 'GiaTriThoaThuan',
 'KhoiLuongThoaThuan',
 'id',
 'company',
 'order',
 'createdAt',
 'updatedAt']

In [38]:
def import_stock(dataframe):
    # company_id = get_company_id()

    prev_close_price = {}
    data = []
    batch_size = 10000

    for _, row in tqdm(dataframe.iterrows(), total=dataframe.shape[0]):
        if pd.isna(row["symbols"]) or pd.isna(row["close"]):
            continue

        symbol = row["symbols"]
        # company = company_id.get(symbol)
        # if company is None:
        #     continue

        # if company != row["company"]:
        #     print(f"{symbol} - {company} - {row['company']}")
        #     break

        close_price = row["close"]

        company_info = company_dict.get(symbol, {})
        exchange = company_info.get("exchange")
        company_id = company_info.get("id")

        if symbol in prev_close_price:
            ceiling_price, floor_price = calculate_ceiling_floor_price(
                exchange, prev_close_price[symbol]
            )
        else:
            ceiling_price, floor_price = 0, 0

        prev_close_price[symbol] = close_price

        id, created_at, updated_at = generate_uuid()

        date = convert_to_timestamp(row["Date"])

        new_stock = Stock(
            id = id,
            createdAt = created_at,
            updatedAt = updated_at,
            openingPrice = round(row["open"], 2),
            closingPrice = round(close_price, 2),
            ceilingPrice = round(ceiling_price, 2),
            floorPrice = round(floor_price, 2),
            highestPrice = round(row["high"], 2),
            lowestPrice = round(row["low"], 2),
            adjustedPrice = round(row["adjust"], 2),
            change = row["change"],
            tradedValue = row["GiaTriKhopLenh"],
            tradedVolume = row["KhoiLuongKhopLenh"],
            agreedValue = row["GiaTriThoaThuan"],
            agreedVolume = row["KhoiLuongThoaThuan"],
            date = date,
            order = 0,
            company = company_id,
        )

        data.append(new_stock)

        if len(data) % batch_size == 0:
            try:
                session.add_all(data)
                session.commit()
                data = []
            except Exception as e:
                session.rollback()
                print(f"Error: {e}")
                break

        # try:
        #     session.add(new_stock)
        #     session.commit()
        # except Exception as e:
        #     session.rollback()
        #     print(f"Error: {e}")
        #     break

In [40]:
try:
    import_stock(data)
except Exception as e:
    session.rollback()
    print(f"Error during import: {e}")

100%|██████████| 3829386/3829386 [40:58<00:00, 1557.78it/s]

## Report

In [36]:
data = read_data("report/report_quarter", raw = True)
data.keys().tolist()

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_9720\2404672310.py:2: DtypeWarning: Columns (18,19,21,22,23,24,25) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(f"{data_path}/raw/{filename}.csv") if raw else pd.read_csv(f"{data_path}/beautiful/{filename}.csv")

['Mã',
 'Quý',
 'Tổng nợ',
 'Nợ ngắn hạn',
 'Tổng tài sản',
 'Lợi nhuận khác',
 'Giá vốn hàng bán',
 'Vốn chủ sở hữu',
 'Lợi nhuận sau thuế',
 'Lợi nhuận tài chính',
 'Doanh thu bán hàng và CCDV',
 'Lợi nhuận gộp về BH và CCDV',
 'Tổng lợi nhuận trước thuế',
 'Tổng tài sản lưu động ngắn hạn',
 'Lợi nhuận sau thuế của công ty mẹ',
 'Tài sản ngắn hạn',
 'Tiền',
 'Các khoảng tương đương tiền',
 'Đầu tư công ty con',
 'Nợ phải trả',
 'Vay dài hạn',
 'Vay ngắn hạn',
 'Đầu tư ngắn hạn',
 'Đầu tư dài hạn',
 'Cổ phiếu ưu đãi',
 'Nợ phải thu khách hàng',
 'Hàng tồn kho',
 'Tài sản cố định hữu hình',
 'M-score',
 'M-score**',
 'F-score',
 "Z-score'",
 'Z-score"',
 'Z-score']

### Import reports

In [39]:
def import_report(dataframe, month=False):
    company_id = get_company_id()
    for _, row in tqdm(dataframe.iterrows(), total=dataframe.shape[0]):
        detail = {
            "Sales revenue": row["Doanh thu bán hàng và CCDV"],
            "Cost of goods sold": row["Giá vốn hàng bán"],
            "Gross profit from sales and services": row["Lợi nhuận gộp về BH và CCDV"],
            "Financial profit": row["Lợi nhuận tài chính"],
            "Other profit": row["Lợi nhuận khác"],
            "Total profit before tax": row["Tổng lợi nhuận trước thuế"],
            "Profit after tax": row["Lợi nhuận sau thuế"],
            "Profit after tax of parent company": row["Lợi nhuận sau thuế của công ty mẹ"],
            "Total current assets": row["Tổng tài sản lưu động ngắn hạn"],
            "Total assets": row["Tổng tài sản"],
            "Short-term liabilities": row["Nợ ngắn hạn"],
            "Total liabilities": row["Tổng nợ"],
            "Owner's equity": row["Vốn chủ sở hữu"],
            "Current assets": row["Tài sản ngắn hạn"],
            "Cash": row["Tiền"],
            "Cash equivalents": row["Các khoảng tương đương tiền"],
            "Investment in subsidiaries": row["Đầu tư công ty con"],
            "Liabilities": row["Nợ phải trả"],
            "Long-term loans": row["Vay dài hạn"],
            "Short-term loans": row["Vay ngắn hạn"],
            "Short-term investments": row["Đầu tư ngắn hạn"],
            "Long-term investments": row["Đầu tư dài hạn"],
            "Preferred stock": row["Cổ phiếu ưu đãi"],
            "Receivables from customers": row["Nợ phải thu khách hàng"],
            "Inventory": row["Hàng tồn kho"],
            "Tangible fixed assets": row["Tài sản cố định hữu hình"],
        }

        quarter = row["Quý"]
        if (quarter is not None) and (quarter is not pd.NA):
            quarter, year = quarter.split("-")
            quarter = int(quarter[-1])
        else:
            quarter = 0
            year = row["Năm"]

        id, created_at, updated_at = generate_uuid()

        if row["Mã"] not in company_id:
            continue

        new_report = Report(
            year=year,
            quarter=quarter,
            month=month,
            detail=json.dumps(detail, ensure_ascii=False),
            mScore1=round(row["M-score"], 2),
            mScore2=round(row["M-score**"], 2),
            fScore1=round(row["F-score"], 2),
            zScore1=round(row["Z-score"], 2),
            zScore2=round(row["Z-score'"], 2),
            zScore3=round(row['Z-score"'], 2),
            company=company_id[row["Mã"]],
            id=id,
            createdAt=created_at,
            updatedAt=updated_at,
            order=0,
        )
        
        try:
            session.add(new_report)
            session.commit()
        except Exception as e:
            # session.rollback()
            print(f"Error: {e} - new_report: {new_report}")
            break

In [40]:
try:
    import_report(data)
except Exception as e:
    session.rollback()
    print(f"Error during import_report: {e}")

  0%|          | 0/64180 [00:00<?, ?it/s]

100%|██████████| 64180/64180 [02:24<00:00, 445.11it/s]